# Change these first
owner: joinfreehold # Your GitHub organization or username
repo: freehold-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Freehold Website (Webflow)
    url: https://www.joinfreehold.com
    icon: https://raw.githubusercontent.com/JoinFreehold/freehold-status/master/assets/freehold-icon-blue.png
  - name: Freehold Stacks Node API
    url: https://stacks-node.joinfreehold.com/v2/info
    icon: https://raw.githubusercontent.com/JoinFreehold/freehold-status/master/assets/freehold-icon-blue.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.joinfreehold.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /freehold-status
  theme: dark
  # themeUrl: https://raw.githubusercontent.com/JoinFreehold/freehold-status/master/assets/freehold.css
  # themeUrl: https://freehold.absorbingchaos.com/freehold.css
  logoUrl: https://raw.githubusercontent.com/JoinFreehold/freehold-status/master/assets/freehold-logo.png
  favicon: https://raw.githubusercontent.com/JoinFreehold/freehold-status/master/assets/freehold-icon-blue.png
  name: Live Status
  introTitle: "**Freehold Status Monitor**"
  introMessage: Status for the Freehold services are shown below.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - whoabuddy

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/30 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
