# Change these first
owner: JoinFreehold # Your GitHub organization or username
repo: freehold-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Freehold
    url: https://www.joinfreehold.com


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /freehold-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Freehold Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Status for the Freehold website is shown below."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/JoinFreehold/freehold-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
